const sampleListings = [
  {
    title: "Cozy Beachfront Cottage",
    description: "Escape to this charming beachfront cottage for a relaxing getaway. Enjoy stunning ocean views and easy access to the beach.",
    image: { url: "https://images.unsplash.com/photo-1552733407-5d5c46c3bb3b?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 1500,
    location: "Malibu",
    country: "United States",
    category: "Beach",
  },
  {
    title: "Modern Loft in Downtown",
    description: "Stay in the heart of the city in this stylish loft apartment. Perfect for urban explorers!",
    image: { url: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 1200,
    location: "New York City",
    country: "United States",
    category: "Iconic cities",
  },
  {
    title: "Mountain Retreat",
    description: "Unplug and unwind in this peaceful mountain cabin. Surrounded by nature, it's a perfect place to recharge.",
    image: { url: "https://images.unsplash.com/photo-1571896349842-33c89424de2d?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 1000,
    location: "Aspen",
    country: "United States",
    category: "Mountains",
  },
  {
    title: "Historic Villa in Tuscany",
    description: "Experience the charm of Tuscany in this beautifully restored villa. Explore the rolling hills and vineyards.",
    image: { url: "https://images.unsplash.com/photo-1566073771259-6a8506099945?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 2500,
    location: "Florence",
    country: "Italy",
    category: "Farms",
  },
  {
    title: "Secluded Treehouse Getaway",
    description: "Live among the treetops in this unique treehouse retreat. A true nature lover's paradise.",
    image: { url: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 800,
    location: "Portland",
    country: "United States",
    category: "Cabins",
  },
  {
    title: "Beachfront Paradise",
    description: "Step out of your door onto the sandy beach. This beachfront condo offers the ultimate relaxation.",
    image: { url: "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 2000,
    location: "Cancun",
    country: "Mexico",
    category: "Beach",
  },
  {
    title: "Rustic Cabin by the Lake",
    description: "Spend your days fishing and kayaking on the serene lake. This cozy cabin is perfect for outdoor enthusiasts.",
    image: { url: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 900,
    location: "Lake Tahoe",
    country: "United States",
    category: "Lakefront",
  },
  {
    title: "Luxury Penthouse with City Views",
    description: "Indulge in luxury living with panoramic city views from this stunning penthouse apartment.",
    image: { url: "https://images.unsplash.com/photo-1622396481328-9b1b78cdd9fd?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 3500,
    location: "Los Angeles",
    country: "United States",
    category: "Iconic cities",
  },
  {
    title: "Ski-In/Ski-Out Chalet",
    description: "Hit the slopes right from your doorstep in this ski-in/ski-out chalet in the Swiss Alps.",
    image: { url: "https://images.unsplash.com/photo-1502784444187-359ac186c5bb?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 3000,
    location: "Verbier",
    country: "Switzerland",
    category: "Mountains",
  },
  {
    title: "Safari Lodge in the Serengeti",
    description: "Experience the thrill of the wild in a comfortable safari lodge. Witness the Great Migration up close.",
    image: { url: "https://images.unsplash.com/photo-1493246507139-91e8fad9978e?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 4000,
    location: "Serengeti National Park",
    country: "Tanzania",
    category: "OMG!",
  },
  {
    title: "Historic Canal House",
    description: "Stay in a piece of history in this beautifully preserved canal house in Amsterdam's iconic district.",
    image: { url: "https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 1800,
    location: "Amsterdam",
    country: "Netherlands",
    category: "Iconic cities",
  },
  {
    title: "Private Island Retreat",
    description: "Have an entire island to yourself for a truly exclusive and unforgettable vacation experience.",
    image: { url: "https://images.unsplash.com/photo-1618140052121-39fc6db33972?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 10000,
    location: "Fiji",
    country: "Fiji",
    category: "Beach",
  },
  {
    title: "Charming Cottage in the Cotswolds",
    description: "Escape to the picturesque Cotswolds in this quaint and charming cottage with a thatched roof.",
    image: { url: "https://images.unsplash.com/photo-1602088113235-229c19758e9f?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 1200,
    location: "Cotswolds",
    country: "United Kingdom",
    category: "Farms",
  },
  {
    title: "Historic Brownstone in Boston",
    description: "Step back in time in this elegant historic brownstone located in the heart of Boston.",
    image: { url: "https://images.unsplash.com/photo-1533619239233-6280475a633a?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 2200,
    location: "Boston",
    country: "United States",
    category: "Iconic cities",
  },
  {
    title: "Beachfront Bungalow in Bali",
    description: "Relax on the sandy shores of Bali in this beautiful beachfront bungalow with a private pool.",
    image: { url: "https://images.unsplash.com/photo-1602391833977-358a52198938?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 1800,
    location: "Bali",
    country: "Indonesia",
    category: "Beach",
  },
  {
    title: "Mountain View Cabin in Banff",
    description: "Enjoy breathtaking mountain views from this cozy cabin in the Canadian Rockies.",
    image: { url: "https://images.unsplash.com/photo-1521401830884-6c03c1c87ebb?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 1500,
    location: "Banff",
    country: "Canada",
    category: "Mountains",
  },
  {
    title: "Art Deco Apartment in Miami",
    description: "Step into the glamour of the 1920s in this stylish Art Deco apartment in South Beach.",
    image: { url: "https://plus.unsplash.com/premium_photo-1670963964797-942df1804579?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 1600,
    location: "Miami",
    country: "United States",
    category: "Iconic cities",
  },
  {
    title: "Tropical Villa in Phuket",
    description: "Escape to a tropical paradise in this luxurious villa with a private infinity pool in Phuket.",
    image: { url: "https://images.unsplash.com/photo-1470165301023-58dab8118cc9?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 3000,
    location: "Phuket",
    country: "Thailand",
    category: "Beach",
  },
  {
    title: "Historic Castle in Scotland",
    description: "Live like royalty in this historic castle in the Scottish Highlands. Explore the rugged beauty of the area.",
    image: { url: "https://images.unsplash.com/photo-1585543805890-6051f7829f98?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 4000,
    location: "Scottish Highlands",
    country: "United Kingdom",
    category: "OMG!",
  },
  {
    title: "Desert Oasis in Dubai",
    description: "Experience luxury in the middle of the desert in this opulent oasis in Dubai with a private pool.",
    image: { url: "https://images.unsplash.com/photo-1518684079-3c830dcef090?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 5000,
    location: "Dubai",
    country: "United Arab Emirates",
    category: "OMG!",
  },
  {
    title: "Rustic Log Cabin in Montana",
    description: "Unplug and unwind in this cozy log cabin surrounded by the natural beauty of Montana.",
    image: { url: "https://images.unsplash.com/photo-1586375300773-8384e3e4916f?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 1100,
    location: "Montana",
    country: "United States",
    category: "Cabins",
  },
  {
    title: "Beachfront Villa in Greece",
    description: "Enjoy the crystal-clear waters of the Mediterranean in this beautiful beachfront villa on a Greek island.",
    image: { url: "https://images.unsplash.com/photo-1602343168117-bb8ffe3e2e9f?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 2500,
    location: "Mykonos",
    country: "Greece",
    category: "Beach",
  },
  {
    title: "Eco-Friendly Treehouse Retreat",
    description: "Stay in an eco-friendly treehouse nestled in the forest. It's the perfect escape for nature lovers.",
    image: { url: "https://images.unsplash.com/photo-1488462237308-ecaa28b729d7?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 750,
    location: "Costa Rica",
    country: "Costa Rica",
    category: "Cabins",
  },
  {
    title: "Historic Cottage in Charleston",
    description: "Experience the charm of historic Charleston in this beautifully restored cottage with a private garden.",
    image: { url: "https://images.unsplash.com/photo-1587381420270-3e1a5b9e6904?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 1600,
    location: "Charleston",
    country: "United States",
    category: "Farms",
  },
  {
    title: "Modern Apartment in Tokyo",
    description: "Explore the vibrant city of Tokyo from this modern and centrally located apartment.",
    image: { url: "https://images.unsplash.com/photo-1480796927426-f609979314bd?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 2000,
    location: "Tokyo",
    country: "Japan",
    category: "Iconic cities",
  },
  {
    title: "Lakefront Cabin in New Hampshire",
    description: "Spend your days by the lake in this cozy cabin in the scenic White Mountains of New Hampshire.",
    image: { url: "https://images.unsplash.com/photo-1578645510447-e20b4311e3ce?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 1200,
    location: "New Hampshire",
    country: "United States",
    category: "Lakefront",
  },
  {
    title: "Luxury Villa in the Maldives",
    description: "Indulge in luxury in this overwater villa in the Maldives with stunning views of the Indian Ocean.",
    image: { url: "https://images.unsplash.com/photo-1439066615861-d1af74d74000?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 6000,
    location: "Maldives",
    country: "Maldives",
    category: "Beach",
  },
  {
    title: "Ski Chalet in Aspen",
    description: "Hit the slopes in style with this luxurious ski chalet in the world-famous Aspen ski resort.",
    image: { url: "https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 4000,
    location: "Aspen",
    country: "United States",
    category: "Mountains",
  },
  {
    title: "Secluded Beach House in Costa Rica",
    description: "Escape to a secluded beach house on the Pacific coast of Costa Rica. Surf, relax, and unwind.",
    image: { url: "https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 1800,
    location: "Costa Rica",
    country: "Costa Rica",
    category: "Beach",
  },
  {
    title: "Luxury Beach Villa in Goa",
    description: "Experience the ultimate beach getaway in this private villa with direct access to Palolem Beach.",
    image: { url: "https://images.unsplash.com/photo-1585543805890-6051f7829f98?q=80&w=2070&auto=format&fit=crop" },
    price: 4500,
    location: "Goa",
    country: "India",
    category: "Beach",
  },
  {
    title: "Cozy Mountain Cabin in Manali",
    description: "Wake up to snow-capped views and the sound of the Beas River in this rustic yet luxurious cabin.",
    image: { url: "https://images.unsplash.com/photo-1587381420270-3e1a5b9e6904?q=80&w=2070&auto=format&fit=crop" },
    price: 2500,
    location: "Manali",
    country: "India",
    category: "Mountains",
  },
  {
    title: "Heritage Farmstay in Punjab",
    description: "Discover authentic Punjabi hospitality in this sprawling farmhouse surrounded by mustard fields.",
    image: { url: "https://images.unsplash.com/photo-1500382017468-9049fed747ef?q=80&w=2000&auto=format&fit=crop" },
    price: 1800,
    location: "Amritsar",
    country: "India",
    category: "Farms",
  },
  {
    title: "Modern Studio in Mumbai",
    description: "Stay in the heart of Bandra with stunning views of the Arabian Sea from this chic high-rise studio.",
    image: { url: "https://images.unsplash.com/photo-1622396481328-9b1b78cdd9fd?q=80&w=2000&auto=format&fit=crop" },
    price: 3500,
    location: "Mumbai",
    country: "India",
    category: "Iconic cities",
  },
  {
    title: "Royal Haveli in Udaipur",
    description: "Live like royalty in this restored 18th-century haveli overlooking Lake Pichola.",
    image: { url: "https://images.unsplash.com/photo-162343168117-bb8ffe3e2e9f?q=80&w=2000&auto=format&fit=crop" },
    price: 4800,
    location: "Udaipur",
    country: "India",
    category: "Iconic cities",
  },
  {
    title: "Backwater Villa in Kerala",
    description: "Enjoy a serene stay in this traditional villa situated on the banks of Vembanad Lake.",
    image: { url: "https://images.unsplash.com/photo-1543968332-f99478b1ebdc?q=80&w=2070&auto=format&fit=crop" },
    price: 3200,
    location: "Alleppey",
    country: "India",
    category: "Lakefront",
  },
  {
    title: "Infinity Pool Retreat in Lonavala",
    description: "Perfect weekend getaway with a private infinity pool overlooking the Western Ghats.",
    image: { url: "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?q=80&w=2000&auto=format&fit=crop" },
    price: 4000,
    location: "Lonavala",
    country: "India",
    category: "Amazing pools",
  },
  {
    title: "Tea Garden Bungalow in Munnar",
    description: "Wake up in the middle of lush green tea plantations in this colonial-style bungalow.",
    image: { url: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?q=80&w=2000&auto=format&fit=crop" },
    price: 2800,
    location: "Munnar",
    country: "India",
    category: "Amazing views",
  },
  {
    title: "Yoga Retreat in Rishikesh",
    description: "Find your inner peace in this hilltop retreat with panoramic views of the Ganges.",
    image: { url: "https://images.unsplash.com/photo-1506126613408-eca07ce68773?q=80&w=2062&auto=format&fit=crop" },
    price: 1500,
    location: "Rishikesh",
    country: "India",
    category: "Mountains",
  },
  {
    title: "Glamping Tents in Jaisalmer",
    description: "Luxury tents in the Thar desert with sunset camel safaris and traditional folk music.",
    image: { url: "https://images.unsplash.com/photo-1518684079-3c830dcef090?q=80&w=2000&auto=format&fit=crop" },
    price: 2200,
    location: "Jaisalmer",
    country: "India",
    category: "OMG!",
  },
  {
    title: "Vintage Plantation Stay in Coorg",
    description: "Immerse yourself in the aroma of fresh coffee in this century-old plantation house.",
    image: { url: "https://images.unsplash.com/photo-1470165301023-58dab8118cc9?q=80&w=2000&auto=format&fit=crop" },
    price: 3000,
    location: "Coorg",
    country: "India",
    category: "Farms",
  },
  {
    title: "Surfers Paradise in Varkala",
    description: "Located right on the cliff, perfect for those looking to catch some waves in the Arabian Sea.",
    image: { url: "https://images.unsplash.com/photo-1502680390469-be75c86b636f?q=80&w=2070&auto=format&fit=crop" },
    price: 1200,
    location: "Varkala",
    country: "India",
    category: "Surfing",
  },
  {
    title: "Snowy A-Frame in Gulmarg",
    description: "Experience a winter wonderland in this cozy A-frame cabin near the ski slopes.",
    image: { url: "https://images.unsplash.com/photo-1502784444187-359ac186c5bb?q=80&w=2000&auto=format&fit=crop" },
    price: 4500,
    location: "Gulmarg",
    country: "India",
    category: "Mountains",
  },
  {
    title: "Island Villa in Havelock",
    description: "Stay in a wooden villa surrounded by tropical forests and turquoise waters.",
    image: { url: "https://images.unsplash.com/photo-1618140052121-39fc6db33972?q=80&w=2000&auto=format&fit=crop" },
    price: 5000,
    location: "Andaman",
    country: "India",
    category: "Beach",
  },
  {
    title: "Artist Loft in Pondicherry",
    description: "Stay in the French Quarter in this sun-drenched loft filled with local art.",
    image: { url: "https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?q=80&w=2000&auto=format&fit=crop" },
    price: 2600,
    location: "Pondicherry",
    country: "India",
    category: "Iconic cities",
  },
  {
    title: "Glass House in Kodaikanal",
    description: "Sleep under the stars in this unique glass-walled cottage hidden in the woods.",
    image: { url: "https://images.unsplash.com/photo-1518780664697-55e3ad937233?q=80&w=2000&auto=format&fit=crop" },
    price: 3800,
    location: "Kodaikanal",
    country: "India",
    category: "Amazing views",
  },
  {
    title: "Treehouse Stay in Athirappilly",
    description: "Wake up to the roar of India's Niagra Falls in this treehouse built on a giant banyan tree.",
    image: { url: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?q=80&w=2000&auto=format&fit=crop" },
    price: 4200,
    location: "Athirappilly",
    country: "India",
    category: "Cabins",
  },
  {
    title: "Luxury Houseboat in Srinagar",
    description: "Glide on Dal Lake in a hand-carved cedar wood houseboat with royal interiors.",
    image: { url: "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?q=80&w=2000&auto=format&fit=crop" },
    price: 3500,
    location: "Srinagar",
    country: "India",
    category: "Lakefront",
  },
  {
    title: "Desert Glamping in Pushkar",
    description: "Stay during the camel fair in these luxury encampments with soul-stirring evening performances.",
    image: { url: "https://images.unsplash.com/photo-1559139225-421502ff48b6?q=80&w=2070&auto=format&fit=crop" },
    price: 2400,
    location: "Pushkar",
    country: "India",
    category: "OMG!",
  },
  {
    title: "Organic Farmstay in Wayanad",
    description: "Learn about traditional spice farming while staying in this bamboo and mud house.",
    image: { url: "https://images.unsplash.com/photo-1500076656116-558758c991c1?q=80&w=2000&auto=format&fit=crop" },
    price: 2000,
    location: "Wayanad",
    country: "India",
    category: "Farms",
  },
  {
    title: "Contemporary Villa in Alibaug",
    description: "Modern minimalist villa with a private lap pool, just a ferry ride away from Mumbai.",
    image: { url: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=2000&auto=format&fit=crop" },
    price: 4500,
    location: "Alibaug",
    country: "India",
    category: "Amazing pools",
  }
];

module.exports = { data: sampleListings };
